# **Netflix Data Cleaning & Preparation**

**Data Loading**

In [1]:
import pandas as pd

data = pd.read_csv("Dataset.csv")
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

**Data Inspection**

In [2]:
data.info()
print('\n',data.shape)
print('\n',data.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

 (8790, 10)

 Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

**Missing Values Check**

In [3]:
data.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

The dataset does not contain missing values .

**Duplicates Check**

In [4]:
print(data.duplicated().sum())

0

The dataset does not contain duplicated records

**Columns Standardization**

In [5]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [6]:
##Remove unnessary spaces
data.columns = data.columns.str.strip()
data['date_added'] = data['date_added'].str.strip()
print('\n',data.columns)
print(data.head(10))
##Convert to standard title format
data.columns = data.columns.str.title()
print('\n',data.columns)

 Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')
  show_id     type                             title             director  \
0      s1    Movie              Dick Johnson Is Dead      Kirsten Johnson
1      s3  TV Show                         Ganglands      Julien Leclercq
2      s6  TV Show                     Midnight Mass        Mike Flanagan
3     s14    Movie  Confessions of an Invisible Girl        Bruno Garotti
4      s8    Movie                           Sankofa         Haile Gerima
5      s9  TV Show     The Great British Baking Show      Andy Devonshire
6     s10    Movie                      The Starling       Theodore Melfi
7    s939    Movie   Motu Patlu in the Game of Zones          Suhas Kadav
8     s13    Movie                      Je Suis Karl  Christian Schwochow
9    s940    Movie          Motu Patlu in Wonderland          Suhas Kadav

          country date_added  release_year rating   duration  \
0   United States  9/25/2021          2020  PG-13     90 min
1          France  9/24/2021          2021  TV-MA   1 Season
2   United States  9/24/2021          2021  TV-MA   1 Season
3          Brazil  9/22/2021          2021  TV-PG     91 min
4   United States  9/24/2021          1993  TV-MA    125 min
5  United Kingdom  9/24/2021          2021  TV-14  9 Seasons
6   United States  9/24/2021          2021  PG-13    104 min
7           India   5/1/2021          2019  TV-Y7     87 min
8         Germany  9/23/2021          2021  TV-MA    127 min
9           India   5/1/2021          2013  TV-Y7     76 min

                                           listed_in
0                                      Documentaries
1  Crime TV Shows, International TV Shows, TV Act...
2                 TV Dramas, TV Horror, TV Mysteries
3                 Children & Family Movies, Comedies
4   Dramas, Independent Movies, International Movies
5                       British TV Shows, Reality TV
6                                   Comedies, Dramas
7  Children & Family Movies, Comedies, Music & Mu...
8                       Dramas, International Movies
9         Children & Family Movies, Music & Musicals

 Index(['Show_Id', 'Type', 'Title', 'Director', 'Country', 'Date_Added',
       'Release_Year', 'Rating', 'Duration', 'Listed_In'],
      dtype='object')

**Value Standardization**

In [7]:
##Check for unique values in each column
print(data['Country'].unique())
print(data['Type'].unique())
print(data['Rating'].unique())

['United States' 'France' 'Brazil' 'United Kingdom' 'India' 'Germany'
 'Pakistan' 'Not Given' 'China' 'South Africa' 'Japan' 'Nigeria' 'Spain'
 'Philippines' 'Australia' 'Argentina' 'Canada' 'Hong Kong' 'Italy'
 'New Zealand' 'Egypt' 'Colombia' 'Mexico' 'Belgium' 'Switzerland'
 'Taiwan' 'Bulgaria' 'Poland' 'South Korea' 'Saudi Arabia' 'Thailand'
 'Indonesia' 'Kuwait' 'Malaysia' 'Vietnam' 'Lebanon' 'Romania' 'Syria'
 'United Arab Emirates' 'Sweden' 'Mauritius' 'Austria' 'Turkey'
 'Czech Republic' 'Cameroon' 'Netherlands' 'Ireland' 'Russia' 'Kenya'
 'Chile' 'Uruguay' 'Bangladesh' 'Portugal' 'Hungary' 'Norway' 'Singapore'
 'Iceland' 'Serbia' 'Namibia' 'Peru' 'Mozambique' 'Ghana' 'Zimbabwe'
 'Israel' 'Finland' 'Denmark' 'Paraguay' 'Cambodia' 'Georgia'
 'Soviet Union' 'Greece' 'West Germany' 'Iran' 'Venezuela' 'Slovenia'
 'Guatemala' 'Jamaica' 'Somalia' 'Croatia' 'Jordan' 'Luxembourg' 'Senegal'
 'Belarus' 'Puerto Rico' 'Cyprus' 'Ukraine']
['Movie' 'TV Show']
['PG-13' 'TV-MA' 'TV-PG' 'TV-14' 'TV-Y7' 'TV-Y' 'PG' 'TV-G' 'R' 'G'
 'NC-17' 'NR' 'TV-Y7-FV' 'UR']

All columns' values are already clean and standardized

**Exporting the cleaned Dataset**

In [8]:
data.to_csv('Cleaned_Dataset.csv' , index=False)
print("Cleaned Data Exported")

Cleaned Data Exported

**Conclusion:**

The Netflix dataset was inspected for data quality issues. No missing values or duplicate records were found, and the checked categorical fields such as Type, Country, and Rating were already standardized. Therefore, no corrective data cleaning operations were required. The validated dataset was exported as Cleaned_Dataset.csv for analysis.